apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: amqp
  name: amqp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amqp
  serviceName: amqp
  template:
    metadata:
      labels:
        app: amqp
    spec:
      containers:
        - image: rabbitmq:3.12-management-alpine
          name: amqp
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-data

      restartPolicy: Always

  volumeClaimTemplates:
      - metadata:
          name: rabbitmq-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10G

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: amqp
  name: amqp
spec:
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "8055"
      port: 8055
      targetPort: 15672
  selector:
    app: amqp

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amqp
  labels:
    app: amqp
spec:
  rules:
    - host: rabbitmq.kube
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amqp
                port:
                  number: 8055
