apiVersion: v1
kind: Service
metadata:
  name: ww-scheduler
  labels:
    app: ww-scheduler
spec:
  clusterIP: None
  ports:
    - port: 7111
      name: gossip
  selector:
    app: ww-scheduler
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: ww-scheduler
  name: ww-scheduler
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ww-scheduler
  serviceName: "ww-scheduler"
  #minReadySeconds: 10
  template:
    metadata:
      labels:
        app: ww-scheduler
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ww-scheduler
          image: waterwheel:local
          args:
            - scheduler
          env:
            - name: WATERWHEEL_AMQP_ADDR
              value: amqp://amqp//
            - name: WATERWHEEL_DB_URL
              value: postgres://postgres:supersecret@db/
            - name: WATERWHEEL_HMAC_SECRET
              value: wwsharedsecret
            - name: WATERWHEEL_NO_AUTHZ
              value: "true"
            - name: WATERWHEEL_SERVER_ADDR
              value: http://ww-api/
            - name: WATERWHEEL_SERVER_BIND
              value: 0.0.0.0:8080
            - name: WATERWHEEL_TASK_ENGINE
              value: kubernetes
            - name: WATERWHEEL_STATSD_SERVER
              value: localhost:8125
            - name: WATERWHEEL_CLUSTER_SEED_NODES
              value: ww-scheduler-0.ww-scheduler.waterwheel.svc.cluster.local:7111,ww-scheduler-1.ww-scheduler.waterwheel.svc.cluster.local:7111
            - name: WATERWHEEL_CLUSTER_GOSSIP_BIND
              value: 0.0.0.0:7111
            - name: WATERWHEEL_CLUSTER_GOSSIP_ADDR
              value: 0.0.0.0:7111

        - name: vector
          image: timberio/vector:0.27.0-alpine
          env:
            - name: INFLUX_TOKEN
              value: my-super-secret-influx-token
          ports:
            - containerPort: 8125
              name: statsd
              protocol: UDP
          volumeMounts:
            - name: vector-conf
              mountPath: "/etc/vector/"
              readOnly: true

      volumes:
        - name: vector-conf
          configMap:
            name: vector-conf
