name: Rust

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install latest nightly
      uses: dtolnay/rust-toolchain@nightly-2023-02-04
      with:
        components: rustfmt, clippy

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test
